package Acme::CPANLists::Import::PerlAdvent::2002_12_06;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2002/6th/] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"Devel::Size"},{module=>"App::XLSperl"}],summary=>"Modules mentioned in Perl Advent Calendar 2002 (day 6)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2002 (day 6)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2002/6th/> (retrieved on 2016-11-07). Visit the URL for the full contents.

