package Acme::CPANLists::Import::PerlAdvent::2002_12_24;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2002/24th/] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"Pixie"}],summary=>"Modules mentioned in Perl Advent Calendar 2002 (day 24)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2002 (day 24)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2002/24th/> (retrieved on 2016-11-07). Visit the URL for the full contents.

