package Acme::CPANLists::Import::PerlAdvent::2002_12_20;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2002/20th/] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"Class::Data::Inheritable"}],summary=>"Modules mentioned in Perl Advent Calendar 2002 (day 20)"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2002 (day 20)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2002/20th/> (retrieved on 2016-11-07). Visit the URL for the full contents.

