package Acme::CPANLists::Import::PerlAdvent::2002;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://perladvent.org/2002/] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"URI::Find"},{module=>"IO::AtomicFile"},{module=>"DBD::SQLite"},{module=>"Test::Builder"},{module=>"Image::Size"},{module=>"Devel::Size"},{module=>"File::MMagic"},{module=>"XML::Handler::AxPoint"},{module=>"XML::SAX"},{module=>"File::Find::Rule"},{module=>"Object::Realize::Later"},{module=>"Benchmark"},{module=>"Test::MockObject"},{module=>"YAML"},{module=>"WWW::Mechanize"},{module=>"Acme::Intraweb"},{module=>"CPANPLUS"},{module=>"Inline::TT"},{module=>"Class::Data::Inheritable"},{module=>"Tie::File"},{module=>"XML::LibXML"},{module=>"Class::DBI"},{module=>"Pixie"},{module=>"Devel::DProf"}],summary=>"Modules mentioned in Perl Advent Calendar 2002"});

1;
# ABSTRACT: Modules mentioned in Perl Advent Calendar 2002

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://perladvent.org/2002/> (retrieved on 2016-11-07). Visit the URL for the full contents.

